version: "3"
services:
  when-database:
    image: postgres:9.5
    hostname: ${POSTGRES_HOST}
    container_name: when-database
    environment:
        POSTGRES_DB: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - when-network

  front:
    image: python:latest
    command: "python -m http.server 3000"
    networks:
      - when-network

  api:
    build:
      context: ..
    networks:
      - when-network
    ports:
      - 8000:8000
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}

  beat:
    build:
      context: ..
    networks:
      - when-network
    command: python -m celery -A when beat -l info
    environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}

  worker:
    build:
      context: ..
    networks:
      - when-network
    command: python -m celery -A when worker -l info
    env_file:
      - .env

  redis:
    image: "redis:latest"
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - when-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - when-network

volumes:
  database:
  redis:

networks:
  when-network:
